In [13]:
import numpy as np
import pandas as pd
dataset=pd.read_csv('zoo.data')

In [14]:
dataset


hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0       1         0     0     1         0        0         1        1   
1       1         0     0     1         0        0         0        1   
2       0         0     1     0         0        1         1        1   
3       1         0     0     1         0        0         1        1   
4       1         0     0     1         0        0         1        1   
..    ...       ...   ...   ...       ...      ...       ...      ...   
96      1         0     0     1         0        0         0        1   
97      1         0     1     0         1        0         0        0   
98      1         0     0     1         0        0         1        1   
99      0         0     1     0         0        0         0        0   
100     0         1     1     0         1        0         0        0   

     backbone  breathes  venomous  fins  legs  tail  domestic  catsize  type  
0           1         1         0     0     4     0         0        1     1  
1           1         1         0     0     4     1         0        1     1  
2           1         0         0     1     0     1         0        0     4  
3           1         1         0     0     4     0         0        1     1  
4           1         1         0     0     4     1         0        1     1  
..        ...       ...       ...   ...   ...   ...       ...      ...   ...  
96          1         1         0     0     2     1         0        1     1  
97          0         1         1     0     6     0         0        0     6  
98          1         1         0     0     4     1         0        1     1  
99          0         1         0     0     0     0         0        0     7  
100         1         1         0     0     2     1         0        0     2  

[101 rows x 17 columns]

In [15]:
dataset.head()

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  backbone  \
0     1         0     0     1         0        0         1        1         1   
1     1         0     0     1         0        0         0        1         1   
2     0         0     1     0         0        1         1        1         1   
3     1         0     0     1         0        0         1        1         1   
4     1         0     0     1         0        0         1        1         1   

   breathes  venomous  fins  legs  tail  domestic  catsize  type  
0         1         0     0     4     0         0        1     1  
1         1         0     0     4     1         0        1     1  
2         0         0     1     0     1         0        0     4  
3         1         0     0     4     0         0        1     1  
4         1         0     0     4     1         0        1     1

In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [19]:
X = dataset.values[:,0:16]
Y = dataset.values[:,-1]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

In [20]:
 X

array([[1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 1, 0, 0],
       ...,
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 0, 0]])

In [21]:
Y

array([1, 1, 4, 1, 1, 1, 1, 4, 4, 1, 1, 2, 4, 7, 7, 7, 2, 1, 4, 1, 2, 2,
       1, 2, 6, 5, 5, 1, 1, 1, 6, 1, 1, 2, 4, 1, 1, 2, 4, 6, 6, 2, 6, 2,
       1, 1, 7, 1, 1, 1, 1, 6, 5, 7, 1, 1, 2, 2, 2, 2, 4, 4, 3, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 7, 4, 1, 1, 3, 7, 2, 2, 3, 7, 4, 2, 1, 7, 4, 2,
       6, 5, 3, 3, 4, 1, 1, 2, 1, 6, 1, 7, 2])

In [22]:
clf=DecisionTreeClassifier(criterion='entropy')

In [23]:
X_train

array([[0, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 1, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [1, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0]])

In [24]:
clf.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [26]:
pred=clf.predict(X_test)

In [27]:
pred

array([4, 2, 2, 2, 6, 1, 1, 1, 4, 2, 1, 6, 2, 1, 1, 2, 1, 7, 4, 1, 1, 6,
       3, 1, 1, 1, 6, 1, 2, 4, 1])

In [28]:
Y_test

array([4, 2, 2, 2, 7, 1, 1, 1, 4, 2, 1, 6, 2, 1, 1, 3, 1, 7, 4, 1, 1, 7,
       3, 1, 1, 1, 6, 1, 2, 4, 1])

In [29]:
print(accuracy_score(Y_test,pred))

0.9032258064516129


In [31]:
print(confusion_matrix(Y_test,pred))

[[14  0  0  0  0  0]
 [ 0  6  0  0  0  0]
 [ 0  1  1  0  0  0]
 [ 0  0  0  4  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  2  1]]


In [33]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       0.86      1.00      0.92         6
           3       1.00      0.50      0.67         2
           4       1.00      1.00      1.00         4
           6       0.50      1.00      0.67         2
           7       1.00      0.33      0.50         3

    accuracy                           0.90        31
   macro avg       0.89      0.81      0.79        31
weighted avg       0.94      0.90      0.89        31

