In [9]:
import numpy as np
import matplotlib.pyplot as mtp    
import pandas as pd 
dataset=pd.read_csv('kmeans.csv')
dataset

X1   X2
0  5.9  3.2
1  4.6  2.9
2  6.2  2.8
3  4.7  3.2
4  5.5  4.2
5  5.0  3.0
6  4.9  3.1
7  6.7  3.1
8  5.1  3.8
9  6.0  3.0

In [12]:
x1=dataset['X1'].values
x2=dataset['X2'].values

In [13]:
x1

array([5.9, 4.6, 6.2, 4.7, 5.5, 5. , 4.9, 6.7, 5.1, 6. ])

In [14]:
x2

array([3.2, 2.9, 2.8, 3.2, 4.2, 3. , 3.1, 3.1, 3.8, 3. ])

In [15]:
x=np.array(list(zip(x1,x2)))

In [16]:
x

array([[5.9, 3.2],
       [4.6, 2.9],
       [6.2, 2.8],
       [4.7, 3.2],
       [5.5, 4.2],
       [5. , 3. ],
       [4.9, 3.1],
       [6.7, 3.1],
       [5.1, 3.8],
       [6. , 3. ]])

In [17]:
C_x=[6.2,6.6,6.5]
C_y=[3.2,3.7,3.0]
Centroid=np.array(list(zip(C_x,C_y)))

In [18]:
Centroid

array([[6.2, 3.2],
       [6.6, 3.7],
       [6.5, 3. ]])

In [20]:
for i in x:
    for j in Centroid:
        dist=np.sqrt(np.sum(np.square(i-j)))
        print(dist)

0.2999999999999998
0.8602325267042621
0.6324555320336757
1.6278820596099712
2.154065922853802
1.902629759044045
0.40000000000000036
0.9848857801796106
0.3605551275463989
1.5
1.9646882704388495
1.8110770276274832
1.2206555615733703
1.2083045973594568
1.562049935181331
1.216552506059644
1.7464249196572978
1.5
1.3038404810405295
1.802775637731994
1.6031219541881394
0.5099019513592785
0.6082762530298221
0.22360679774997916
1.2529964086141672
1.5033296378372907
1.61245154965971
0.2828427124746193
0.9219544457292886
0.5
